name: mne
channels:
- defaults
dependencies:
- python>=3.6
- pip
- mkl
- numpy
- scipy
- matplotlib
- pyqt>=5.9
- vtk>=8
- nose
- coverage
- pytest
- pytest-cov
- flake8
- pygments
- sphinx
- numpydoc
- pip:
  - "https://api.github.com/repos/enthought/traits/zipball/a99b3f64d50c5f7f28ffc01bf69419b061f9e976"
  - "https://api.github.com/repos/enthought/pyface/zipball/6a0cac149d56293482bb828a7d98122667c773be"
  - "https://api.github.com/repos/enthought/traitsui/zipball/e366ad3886d3c39bedb96e83bab447d31c4ab725"
  - "https://api.github.com/repos/enthought/mayavi/zipball/master"
  - nibabel
  - pytest-sugar
  - pytest-faulthandler
  - imageio
  - codecov
  - sphinx-gallery
